<!-- TODO is there a way to get these CSS class names dynamically? -->

<div class="columns">

  <div class="side-col" id="page:left">
    <h2>Salsify Connect<h2>
    <div id="salsify-menu">
      <?php echo $this->getChildHtml('salsify-menu'); ?>
    </div>
  </div>

  <div class="main-col" id="content">
    TODO
    <!--
    <?php echo $this->getChildHtml('salsify-content'); ?>
    -->
  </div>

</div>