<!--
  TODO we're relying on CSS classes that I inspected from elsewhere in Magento.
       Maybe they can be deduced programatically?
  -->

<!--
<div class="columns">
  <div class="side-col" id="page:left">
    <h1>Salsify Connect</h1>
    <?php echo $this->getChildHtml('menu_left'); ?>
  </div>

  <div class="main-col" id="content">
    TODO need the actual content to go here
  </div>
</div>
-->

TESTING