<div class="content-header">
  <table class="grid-header">
  <tr>
    <td><h3>Manage Salsify Connect</h3></td>
    <td class="a-right">
      <button onclick="editForm.submit()" class="scalable save" type="button"><span>Save</span></button>
    </td>
  </tr>
  </table>
</div>

<div class="entry-edit">
  <form id="salsify_configuration_edit_form" name="salsify_configuration_edit_form" method="post" action="<?php echo $this->getPostActionUrl(); ?>">

    <?php // security requirement by Magento ?>
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    
    <h4 class="icon-head head-edit-form fieldset-legend">Salsify Account Information</h4>
    <fieldset>
      <table class="form-list">
        <tr>
          <td class="label">API Key <span class="required">*</span></td>
          <td class="input-ele"><input class="input-text required-entry" name="configuration[api_key]" value="<?php echo $this->getApiKey(); ?>" /></td>
        </tr>
        <tr>
          <td class="label">Salsify Application URL <span class="required">*</span></td>
          <td class="input-ele"><input class="input-text required-entry" name="configuration[url]" value="<?php echo $this->getSalsifyUrl(); ?>" /></td>
        </tr>
      </table>
    </fieldset>
  </form>
</div>

<script type="text/javascript">
  var editForm = new varienForm('salsify_configuration_edit_form');
</script>

<div id="get-salsify">
  <h2>Don't have a Salsify account?</h2>
  <p>
    Head to <a href="http://www.salsify.com/">Salsify.com</a> to sign up!
  </p>
</div>